In [1]:
from ctu_crs import CRS97
import numpy as np
import camera

In [2]:
robot = CRS97()

Firmware version : MARS8 v1.0 build Pi Oct  2 2017 11:06:45


In [3]:
robot.initialize(home=False)

In [10]:
robot.release()

In [7]:
robot.reset_motors()

In [4]:
cam = camera.Camera()

In [5]:
img = robot.grab_image()

In [6]:
cam.detect_markers(img)

(array([[[ 0.00973281,  3.14942045,  0.05256464]],
 
        [[ 0.00449514, -2.96331698,  0.06674811]]]),
 array([[[  94.53015923,   60.64455999, 1170.78304312]],
 
        [[  19.32377282,  -14.70723296, 1170.75098683]]]),
 array([[1],
        [2]], dtype=int32))

In [7]:
midpoint, R = cam.get_mid_points(img)

[[1]
 [2]]
3.108240556195193 -0.008383394941311878 3.135551791560725


In [8]:
midpoint

array([  56.92696603,   22.96866351, 1170.76701498])

In [9]:
R

array([[-0.99998175,  0.00604083,  0.        ],
       [-0.00604083, -0.99998175,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [39]:
pose1 = np.array([[-1,  0, 0, 0.35],
       [ 0,  1,  0, 0.1],
       [ 0,  0, -1, 0.2],
       [ 0.0,  0.0,  0.0, 1.0]])

In [41]:
move_robot_to(pose1)

In [37]:
def move_robot_to(position):
    q0 = robot.q_home
    ik_sols = robot.ik(position)
    assert len(ik_sols) > 0
    closest_solution = min(ik_sols, key=lambda q: np.linalg.norm(q - q0))
    robot.move_to_q(closest_solution)
    robot.wait_for_motion_stop()

In [30]:
zadani = np.array([0, 0, 220])

In [26]:
cil = np.array([0.35, 0, 0.22])

In [3]:
pointKamera = R@zadani + midpoint
pointKamera

NameError: name 'R' is not defined

In [1]:
diff = np.array([-477.5, 104.8, 597.3])


NameError: name 'np' is not defined