In [1]:
from ctu_crs import CRS97
import numpy as np
import camera

In [2]:
robot = CRS97()

Firmware version : MARS8 v1.0 build Pi Oct  2 2017 11:06:45


In [27]:
robot.initialize(home=False)

In [41]:
robot.soft_home()

In [25]:
robot.release()

In [7]:
robot.reset_motors()

In [5]:
cam = camera.Camera()

In [29]:
img = robot.grab_image()

In [30]:
cam.detect_markers(img)

(array([[[ 2.97062143, -0.0276295 , -0.0396568 ]],
 
        [[ 2.99902341, -0.03287964,  0.06386823]]]),
 array([[[ -44.08055028,  123.19143709, 1182.38985452]],
 
        [[-119.99675582,   48.01454865, 1181.59638791]]]),
 array([[2],
        [1]], dtype=int32))

In [31]:
midpoint, R = cam.get_mid_points(img)

[[2]
 [1]]
2.9707337148898376 0.024922504655299906 -0.020735714444447828


In [32]:
midpoint

array([ -82.03865305,   85.60299287, 1181.99312122])

In [33]:
R

array([[ 0.99978502, -0.02073423,  0.        ],
       [ 0.02073423,  0.99978502,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [34]:
p_cam_h = np.append(midpoint, 1.0)


In [35]:
TR_C = [[-4.91410691e-03,  9.98341087e-01, -5.73665839e-02,  4.90644721e+02],
 [ 9.97906036e-01,  1.19594619e-03, -6.46692634e-02,  2.38816422e+01],
 [-6.44933754e-02, -5.75642520e-02, -9.96256474e-01 , 1.19549166e+03],
 [ 0.00000000e+00 , 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]

In [36]:
p_robot_h = TR_C @ p_cam_h
p_robot = p_robot_h[:3] * 0.001
p_robot

array([ 0.50870195, -0.13432147,  0.01828664])

In [39]:
pose1 = np.array([[-1,  0, 0, 0.508],
       [ 0,  1,  0, -0.134],
       [ 0,  0, -1, 0.2],
       [ 0.0,  0.0,  0.0, 1.0]])

In [40]:
move_robot_to(pose1)

In [22]:
def move_robot_to(position):
    q0 = robot.q_home
    ik_sols = robot.ik(position)
    assert len(ik_sols) > 0
    closest_solution = min(ik_sols, key=lambda q: np.linalg.norm(q - q0))
    robot.move_to_q(closest_solution)
    robot.wait_for_motion_stop()

In [30]:
zadani = np.array([0, 0, 220])

In [26]:
cil = np.array([0.35, 0, 0.22])

In [3]:
pointKamera = R@zadani + midpoint
pointKamera

NameError: name 'R' is not defined

In [1]:
diff = np.array([-477.5, 104.8, 597.3])


NameError: name 'np' is not defined