In [1]:
from ctu_crs import CRS97
import numpy as np

In [2]:
robot = CRS97()

Firmware version : MARS8 v1.0 build Pi Oct  2 2017 11:06:45


In [41]:
robot.initialize(home=False)

In [40]:
robot.release()


In [ ]:
robot.soft_home()
robot.close()  # close the connection


In [25]:
robot.reset_motors()

In [42]:
robot.soft_home()

In [57]:
#TEST
q = robot.get_q()  # get current joint configuration
robot.move_to_q(q + [0.0, -0.1, 0.0, 0.0, 0.0, 0.0])  # move robot all values in radians
robot.wait_for_motion_stop() # wait until the robot stops

In [6]:
import puzzle

In [94]:
PuzzleA = puzzle.PuzzleA()
line1 = PuzzleA.components[0]
points1 = line1.get_descrete_points()
plane1 = line1.get_normal_plane()

In [95]:
points1

array([[  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,  22.22222222],
       [  0.        ,   0.        ,  44.44444444],
       [  0.        ,   0.        ,  66.66666667],
       [  0.        ,   0.        ,  88.88888889],
       [  0.        ,   0.        , 111.11111111],
       [  0.        ,   0.        , 133.33333333],
       [  0.        ,   0.        , 155.55555556],
       [  0.        ,   0.        , 177.77777778],
       [  0.        ,   0.        , 200.        ]])

In [16]:
plane1[1]

np.float64(1.0)

In [19]:
x = plane1[2]
y = plane1[3]
z = plane1[1]
p = points1[9] * 0.001

SE3 = np.array([[x[0], y[0], z[0], p[0]],
           [x[1], y[1], z[1], p[1]],
           [x[2], y[2], z[2], p[2]],
           [0, 0, 0, 1]])


SE3

array([[ 0. , -1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0.2],
       [ 0. ,  0. ,  0. ,  1. ]])

In [85]:
ZeroZeroZero = robot.get_q()
current_pose = robot.fk(robot.get_q())

In [86]:
current_pose

array([[-9.32876463e-10,  5.34097055e-05,  9.99999999e-01,
         3.09698782e-01],
       [-2.19951609e-05,  9.99999998e-01, -5.34097055e-05,
        -1.14054001e-05],
       [-1.00000000e+00, -2.19951610e-05,  2.41878630e-10,
         8.43479324e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [60]:
# current_pose[:3, 3] -= np.array([0.0, 0.0, 0.1])
# current_pose

In [61]:
pos = SE3[:3, 3] - current_pose[:3, 3]
pos

array([-0.44592542,  0.03348242,  0.03689838])

In [35]:
pose1 = np.array([[-1,  0, 0, 0.4],
       [ 0,  1,  0, 0],
       [ 0,  0, -1, 0.2],
       [ 0.0,  0.0,  0.0, 1.0]])
pose2 = pose1
# pose1 = np.array([[0,  0, -0.9, 4.37467139e-01],
#        [ -0.9,  0,  0, -25.70933461e-02],
#        [ 0,  +0.9, 0, 50.95351819e-02],
#        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00]])

In [36]:

q0 = robot.q_home
ik_sols = robot.ik(pose1)
assert len(ik_sols) > 0
closest_solution = min(ik_sols, key=lambda q: np.linalg.norm(q - q0))
robot.move_to_q(closest_solution)
robot.wait_for_motion_stop()

In [100]:
def move_robot_to(position):
    q0 = robot.q_home
    ik_sols = robot.ik(position)
    assert len(ik_sols) > 0
    closest_solution = min(ik_sols, key=lambda q: np.linalg.norm(q - q0))
    robot.move_to_q(closest_solution)
    robot.wait_for_motion_stop()

In [97]:
points = points1 * 0.001
points

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.02222222],
       [0.        , 0.        , 0.04444444],
       [0.        , 0.        , 0.06666667],
       [0.        , 0.        , 0.08888889],
       [0.        , 0.        , 0.11111111],
       [0.        , 0.        , 0.13333333],
       [0.        , 0.        , 0.15555556],
       [0.        , 0.        , 0.17777778],
       [0.        , 0.        , 0.2       ]])

In [121]:
pose1

array([[-9.91060474e-01,  1.28667136e-01, -3.52690498e-02,
         4.00000000e-01],
       [ 1.28583986e-01,  9.91687837e-01,  4.62524074e-03,
         0.00000000e+00],
       [ 4.55710042e-02,  4.88582751e-05, -9.99367150e-01,
         4.00000000e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [142]:
for i in range(len(points)):
    pose = pose1.copy()
    pose[:3, 3] = pose1[:3, 3] - points[i]
    print(pose[2][3])
    move_robot_to(pose)

0.4
0.3777777777777778
0.35555555555555557
0.33333333333333337
0.3111111111111111
0.2888888888888889
0.2666666666666667
0.24444444444444446
0.22222222222222224
0.2


In [291]:
robot.initialize(home=False)

In [371]:
robot.release()

In [373]:
robot.reset_motors()

In [38]:
img = robot.grab_image()

# 'img' is a NumPy array containing the image data.
# You can now process it, for example, using a library like OpenCV.
if img is not None:
    print(f"Successfully grabbed image with shape: {img.shape}")

Successfully grabbed image with shape: (1200, 1920, 3)
